### ISSUE TITLE
389DS default search limit

### ISSUE THREAD

**Issue by bastiak** [peterpakos/ipa_check_consistency#11]
389DS has configured limit 2000 entries for ldapsearch. Script may stuck at state 2000 entries in large environments. Users should be warned when a count of entries is > than 2000

**Comment by bastiak** [comment]
Respectively it is possible to detect current value of nslapd-sizelimit on each server
http://directory.fedoraproject.org/docs/389ds/howto/howto-ldapsearchmanyattr.html

**Comment by peterpakos** [comment]
I've looked into this today, it seems that the nsslapd-sizelimit is not enforced for cn=Directory Manager.

Closing off as there is nothing to be improved here.
