### ISSUE TITLE
ldapwhoami fails on Centos7.2 with the rpm-supplied freeipa.

### ISSUE THREAD

**Issue by icepic** [peterpakos/ipa_check_consistency#13]
If one leaves that test out, it actually runs and works fine for me with:
ipa-server-4.2.0-15.0.1.el7.centos.6.1.x86_64,
with the test in, ldapwhoami given useful credentials returns:
Enter LDAP Password: 
ldap_parse_result: Protocol error (2)
	additional info: unsupported extended operation
Result: Protocol error (2)
Additional info: unsupported extended operation

**Comment by peterpakos** [comment]
@icepic, thanks for taking the time to raise this issue.

I'm also on ipa-server-4.2.0-15.0.1.el7.centos.18.x86_64 and I'm failing to see the problem.

How can I replicate it?

**Comment by icepic** [comment]
This is how it looks at my end:
 ldapsearch -x -D 'cn=Directory Manager' -W -ZZ -h ipaserver
<enter pw>
<lots of ldap output>
ldapwhoami -x -D 'cn=Directory Manager' -W -ZZ -h ipaserver
<enter pw>
ldap_parse_result: Protocol error (2)
	additional info: unsupported extended operation
Result: Protocol error (2)
Additional info: unsupported extended operation

more info:
ldapwhoami -VV
ldapwhoami: @(#) $OpenLDAP: ldapwhoami 2.4.40 (Mar 31 2016 15:24:47) $
	mockbuild@worker1.bsys.centos.org:/builddir/build/BUILD/openldap-2.4.40/openldap-2.4.40/clients/tools
	(LDAP library: OpenLDAP 20440)

ldapsearch -VV
ldapsearch: @(#) $OpenLDAP: ldapsearch 2.4.40 (Mar 31 2016 15:24:47) $
	mockbuild@worker1.bsys.centos.org:/builddir/build/BUILD/openldap-2.4.40/openldap-2.4.40/clients/tools
	(LDAP library: OpenLDAP 20440)

**Comment by peterpakos** [comment]
@icepic, as discussed, I'm unable to replicate this issue.

Have you made any progress?

**Comment by peterpakos** [comment]
Closing as unable to replicate the problem.

Feel free to re-open if you can provided a reproducible scenario.
