### ISSUE TITLE
Port code to python

### ISSUE THREAD

**Issue by MartinBasti** [peterpakos/ipa_check_consistency#17]
Why python?

* better readability
* plugins support
* multiple output formaters support
* more power

Sub tasks
- [x] setup.py
- [x] travis CI checks
- [x] pylint
- [x] Basic python multiprocessing structures
- [x] Plugin system
- [x] Output formaters system
- [ ] config file
- [ ] documentation

Options ported:
- [x] -H  List of IPA servers
- [ ] -d  IPA domain
- [x] -s  LDAP root suffix, if not domain based
- [ ] -D  BIND DN
- [x] -W  BIND password
- [ ] -p  Password file
- [x] -n  Nagios plugin mode
- [ ] -w  Warning threshold (0-12), number of failed checks before alerting (default: 1)
- [ ] -c  Critical threshold (0-12), number of failed checks before alerting (default: 2)
- [x] -h  Print this help summary page
- [ ] -v  Print version number

Checks:
- [x]     users   - Active Users
- [x]     ustage  - Stage Users
- [x]     upres   - Preserved Users
- [x]     ugroups - User Groups
- [x]     hosts   - Hosts
- [x]     hgroups - Host Groups
- [x]     hbac    - HBAC Rules
- [x]     sudo    - SUDO Rules
- [x]     zones   - DNS Zones
- [ ]     ldap    - LDAP Conflicts
- [ ]     ghosts  - Ghost Replicas
- [ ]     bind    - Anonymous BIND

Regressions:
- [ ] support both FQDN and relative hostnames
- [ ] state column is not working
- [ ] keep order of plugins (alphabetically or by order in files?)

**Comment by Akasurde** [comment]
@mbasti-rh I would love to help in this work. I wrote following checks `Staged users` and `Preserved Users` here - a414d540a4e73937fd89af249b5d4aa9bd3cc07d

**Comment by mbasti-rh** [comment]
@Akasurde I would like to have PR #16 merged first before any continuation of work

**Comment by peterpakos** [comment]
@mbasti-rh, I'd prefer for the PRs go into a separate branch or even a separate GitGub project altogether. The reason for this is I have this repo set as remote on many machines in the production environment plus it's synced with our internal repository where we have an internal code review process in place.

Any chance you can re-issue PRs for a separate branch called python, or something?

I could then merge them straight away.

**Comment by mbasti-rh** [comment]
it is simple to create PR against different branch, just give me a name

**Comment by peterpakos** [comment]
@mbasti-rh, I've just created new branch called python.
