### ISSUE TITLE
[RFE] automatically get all IPA servers from LDAP

### ISSUE THREAD

**Issue by MartinBasti** [peterpakos/ipa_check_consistency#23]
Instead of specifying the IPA servers manually, it is possible to download all hostnames from LDAP (only one hostname is needed, it could be --fetch-servers-from=ipa001.example.com option)

**Comment by peterpakos** [comment]
@MartinBasti, I like the idea. I thought about implementing this in the past but never got round to actually doing it. Do you know which DN is best suited to grab the list of servers?

**Comment by peterpakos** [comment]
Having IPA domain specified, I guess it's also possible to grab the list of servers from DNS using SRV entries. What do you think, @MartinBasti?

**Comment by MartinBasti** [comment]
@peterpakos I like the DNS way more
