### ISSUE TITLE
Option to use GSSAPI (Kerberos) for auth

### ISSUE THREAD

**Issue by dalston** [peterpakos/ipa_check_consistency#29]
Great script, btw!  I learned some coding tricks from it too :^)

Sometimes it is more convenient to authenticate the LDAP queries using a kerberos ticket.  That way my ssh login to the server usually generates the credentials for me automatically.  When the kerberos ticket isn't there I can use "kinit <username>" to get one.

I've attached a version of your script that adds a "-Y" option to authenticate the ldapsearch using "-Y GSSAPI".
[ipa_check_consistency-GSSAPI.txt](https://github.com/peterpakos/ipa_check_consistency/files/1216016/ipa_check_consistency-GSSAPI.txt)

The diff from your script that I modified is below..
-snip-
workstation:~> diff ipa_check_consistency.orig ipa_check_consistency-GSSAPI 
25c25
< readonly APP_VER="1.2.1"
---
> readonly APP_VER="1.0.0"
43c43
< declare -a NAGIOSOPTS=("all" "users" "ustage" "upres" "ugroups" "hosts" "hgroups" "hbac" "sudo" "zones" "certs" "ldap" "ghosts" "bind" "msdcs")
---
> declare -a NAGIOSOPTS=("all" "users" "ustage" "upres" "ugroups" "hosts" "hgroups" "hbac" "sudo" "zones" "certs" "ldap" "ghosts" "bind")
58d57
<                         ['msdcs']='Microsoft ADTrust' \
85a85
> -Y  Use Kerberos ticket in current keytab for authentication
104d103
<     msdcs   - Microsoft ADTrust
127c126
<   while getopts ":vhd:D:W:s:p:H:n:w:c:" opt; do
---
>   while getopts ":vhd:D:W:s:p:H:n:w:c:Y" opt; do
174a174,176
>       Y)
>         GSSAPI_BIND="true"
>         ;;
274c276
<   if [[ -z "$BINDPW" ]]; then
---
>   if [[ -z "$BINDPW" ]] && [[ -z "$GSSAPI_BIND" ]]; then
285a288,289
>   [[ -n "$GSSAPI_BIND" ]] && return 0
> 
319,320c323
<   # shellcheck disable=SC2046
<   if diff --from-file $(grep -lv 'N/A' -r "$dir" || printf "%s" "$dir") &>/dev/null; then
---
>   if diff --from-file "$dir"/* &>/dev/null; then
333,335c336,344
<   ldapsearch -o ldif-wrap=no -ZZ -LLLx -h "${server}" \
<     -D "$BINDDN" -w "$BINDPW" -s "$scope" \
<     -b "$base" "$filter" "$attr" 2>/dev/null
---
>   if [[ -n "$GSSAPI_BIND" ]]; then
>     ldapsearch -o ldif-wrap=no -ZZ -LLL -h "${server}" \
>       -Y GSSAPI -s "$scope" \
>       -b "$base" "$filter" "$attr" 2>/dev/null
>   else
>     ldapsearch -o ldif-wrap=no -ZZ -LLLx -h "${server}" \
>       -D "$BINDDN" -w "$BINDPW" -s "$scope" \
>       -b "$base" "$filter" "$attr" 2>/dev/null
>   fi
725,754d733
< msdcs() {
<   local server="" state=""
<   local dir="${TMP_DIR}/dns_msdcs"
< 
<   mkdir -p "$dir"
<   printf "%-${FIRST_COLUMN}s" "Microsoft ADTrust"
<   for server in "${SERVERS[@]}"; do
<     (
<     if (dig +short _kerberos._tcp.Default-First-Site-Name._sites.dc._msdcs."${DOMAIN}" SRV | grep -q "${server}"); then
<       state="YES"
<     else
<       state="NO"
<     fi
<     printf "%s" "$state" > "${dir}/${server}"
<     ) &
<   done
<   wait
<   for server in "${SERVERS[@]}"; do
<     printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
<   done
<   state="$(is_consistent "$dir")"
<   printf "%-${LAST_COLUMN}s\n" "$state"
<   if [[ $NAGIOS -eq 1 ]]; then
<     printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
<     if [[ "$NAGIOSREPORT" == "msdcs" ]]; then
<       printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
<     fi
<   fi
< }
< 
875d853
<   msdcs > "$TMP_DIR/msdcs.out" &
895d872
<   printf "%s\n" "$(< "${TMP_DIR}/msdcs.out")"
-snip-

**Comment by peterpakos** [comment]
I like the idea and I considered it before. Unfortunately using any account other than 'Directory Manager' fails to pull some restricted data due to it being only available to the DM (including Anonymous BIND and Ghost Replicas):

`Ghost Replicas      ERROR      ERROR      ERROR      ERROR      ERROR      ERROR      FAIL`

Even the admin account has less privileges than the Directory Manager. I should probably hardcode the Bind DN and remove option -D because of this.
