### ISSUE TITLE
Permissions required for non Directory Admin uid?

### ISSUE THREAD

**Issue by anthonyclarka2** [peterpakos/ipa_check_consistency#30]
Hello,

I was trying to figure out how to run this as a read-only user to incorporate it into my Zabbix monitoring infrastructure.

Do you have a list of the parts of the LDAP tree that your script reads?

It's fantastic, by the way.  This is perfect for what we need and I'm really grateful to you for writing it.

Thanks,

**Comment by peterpakos** [comment]
Hi, @anthonyclarka2. I'm glad you're liking the script.

These should be all LDAP paths the script queries:

```
$ grep query_ldap ipa_check_consistency -A1 | grep 'cn='
    if ! count=$(query_ldap "cn=users,cn=accounts,${SUFFIX}" \
      "cn=staged users,cn=accounts,cn=provisioning,${SUFFIX}" \
      "cn=deleted users,cn=accounts,cn=provisioning,${SUFFIX}" \
    if ! count=$(query_ldap "cn=groups,cn=accounts,${SUFFIX}" \
    if ! count=$(query_ldap "cn=computers,cn=accounts,${SUFFIX}" \
    if ! count=$(query_ldap "cn=hostgroups,cn=accounts,${SUFFIX}" \
    if ! count=$(query_ldap "cn=hbac,${SUFFIX}" \
    if ! count=$(query_ldap "cn=sudorules,cn=sudo,${SUFFIX}" \
    if ! count=$(query_ldap "cn=dns,${SUFFIX}" \
    if ! state=$(query_ldap "cn=config" "(cn=config)" \
      "cn=replica,cn=${suffix},cn=mapping tree,cn=config" \
```

Some of them are only accessible by `cn=Directory Manager' hence it is not possible to use an ordinary user account (or even admin account) to query them.

I've had a discussion with FreeIPA developers about this on #freeipa channel and sadly there was no easy way around this.

I may even hardcode the BINDDN as there is no benefit of using any other than `cn=Directory Manager'.

If you do find a way to use a read-only acocunt, please let me know.

**Comment by anthonyclarka2** [comment]
Thanks for the answer!  It's unfortunate that the perms are setup in that way.  I'll report back if I do manage to figure out a way around this restriction.
