### ISSUE TITLE
BIND failed to all servers, check connection details and try again.

### ISSUE THREAD

**Issue by larizzo** [peterpakos/ipa_check_consistency#31]
I can't figure out what I'm doing wrong, no matter what I do I get the below error:

```
./ipa_check_consistency -H "mtl-ipa01d mtl-ipa02d" -d tdppd.lab -n users -W password
BIND failed to all servers, check connection details and try again.
```

**Comment by peterpakos** [comment]
@larizzo, what version of FreeIPA are you using?

I've just tried it in a test environment (FreeIPA 4.2.0, CentOS 7.2) and it worked OK.

Are you definitely using cn=Directory Manager's password?

**Comment by larizzo** [comment]
@peterpakos Thanks for the reply!
freeipa 4.4
Yes definitely using correct password.
I'm wondering if the code is designed for 3 dc=? I saw you have ipa.domain.com where I have domain.com?

**Comment by larizzo** [comment]
I put the hosts FQDN and it works now! Thanks!

**Comment by peterpakos** [comment]
@larizzo, I'm guessing the node address mtl-ipa01d.tdppd.lab is not correct then?
